### ISSUE TITLE
cargo install doesn’t work anymore

### ISSUE THREAD

**Issue by alarig** [cardoe/cargo-ebuild#28] opened 2019-12-04 18:35 UTC
Hi,

I used cargo-ebuild to make an ebuild: https://git.grifon.fr/alarig/SwordArMor-gentoo-overlay/src/branch/master/net-misc/routinator/routinator-0.6.4.ebuild

But I can’t install it, I have an error:
```
>>> Source compiled.
>>> Test phase [not enabled]: net-misc/routinator-0.6.4

>>> Install net-misc/routinator-0.6.4 into /var/tmp/portage/net-misc/routinator-0.6.4/image
error: Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if 
you want to simply build the package.
 * ERROR: net-misc/routinator-0.6.4::SwordArMor failed (install phase):
 *   cargo install failed
 * 
 * Call stack:
 *     ebuild.sh, line 125:  Called src_install
 *   environment, line 965:  Called cargo_src_install
 *   environment, line 719:  Called die
 * The specific snippet of code:
 *       cargo install -j $(makeopts_jobs) --root="${D}/usr" $(usex debug --debug "") "$@" || die "cargo install failed";
 * 
 * If you need support, post the output of `emerge --info '=net-misc/routinator-0.6.4::SwordArMor'`,
 * the complete build log and the output of `emerge -pqv '=net-misc/routinator-0.6.4::SwordArMor'`.
 * The complete build log is located at '/var/tmp/portage/net-misc/routinator-0.6.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-misc/routinator-0.6.4/temp/environment'.
 * Working directory: '/var/tmp/portage/net-misc/routinator-0.6.4/work/routinator-0.6.4'
 * S: '/var/tmp/portage/net-misc/routinator-0.6.4/work/routinator-0.6.4'
```

**Comment by cardoe** [comment] 2019-12-22 22:16
This is really an issue with cargo.eclass and a duplicate of #24. I'll look at enabling it globally in the tree as all versions of Rust in the tree should be new enough.

**Comment by cardoe** [comment] 2019-12-23 04:04
https://github.com/gentoo/gentoo/pull/14097 suggests changing the defaults here to something sensible given the versions of cargo/rust in the tree.

**Comment by cardoe** [comment] 2019-12-28 01:22
The default has now been updated in the tree.

**Closed by cardoe** 2019-12-28 01:22 UTC
